[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "rm -rf node_modules/.cache || true",
  "npm install --include=dev --no-audit --no-fund"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
